### ISSUE TITLE
Organização do Repositório

### ISSUE THREAD

**Issue by renorram** [YapayPagamentos/yapay-magento1#4]
Por favor, peço que utilizem o repositório de forma correta para que possamos contribuir com o módulo, pois de longe qualquer desenvolvedor sabe que não é boa prática subir arquivos compactados para o repositório.

**Comment by abnava** [comment]
Boa tarde,

O arquivo compactado era devido a grande quantidade de pessoas não desenvolvedoras que utilizam nosso módulo.

Já atualizei o repositório, vamos manter a pasta e o arquivo compactado.

Atenciosamente,
Ana Nava Bagagi
Produtos | Integração
Yapay

**Comment by renorram** [comment]
@abnava obrigado pela resposta, entendo o ponto de vista de vocês, porém posteriormente vocês poderiam usar o recurso de releases do github que já gera um zip do código de vocês e coloca na área de releases do repositório, é uma boa! de toda forma obrigado pela atenção!
